### ISSUE TITLE
MLF Date-A-Scientist Grade Summary

### ISSUE THREAD

**Issue by mackenzieyoung** [kieranmaine/DateAScientistProject#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Exploration of Data
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, you explore the data significantly, and your experimental questions are logical and based on your data exploration. Features chosen to answer the question make sense. Very nice job explaining your data exploration in your presentation as well. 
 
### Criteria 3: Machine Learning Techniques used correctly
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your algorithms are used correctly and the correct conclusions are drawn from the results. I especially like how you broke your research questions down in terms of classification and regression.
 
### Criteria 4: Report: Are conclusions clear and supported by data?
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Your questions are stated clearly, and the results of your regression algorithms and classification algorithms are shown. Your conclusions are clearly stated and based on evidence. Very nice job looking beyond just accuracy when evaluating your model performance.

### Criteria 5: Code formatting
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Your code is well formatted and easy to read, nice job using Jupyter notebooks to make it even easier to follow along with your code.
 
### Overall Score: 20/20
Great job!

**Comment by kieranmaine** [comment]
thanks for the feedback @mackenzieyoung I really enjoyed the course :)
